name: Build

on: push

jobs:
  build:
    runs-on: rehosting-arc
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install xz-utils curl p7zip-full jq sqlite3 -y
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: nix-community/cache-nix-action@v5
        with:
          primary-key: ${{ runner.os }}-nix-store
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix flake check
      - run: nix build
      - run: tar -chzvf hyperfs.tar.gz result

      - uses: actions/upload-artifact@v4
        with:
          path: ./hyperfs.tar.gz
